### ISSUE TITLE
Geofencing example

### ISSUE THREAD

**Issue by jmkiley** [mapbox/ios-sdk-examples#102]
It would be great to have an example that shows how to visualize geofencing with Mapbox iOS SDK. For example, how to detect and change a map based on whether a user is in a region.

cc @captainbarbosa

**Comment by captainbarbosa** [comment]
It would be awesome to show the geofence too. That might be blocked by https://github.com/mapbox/mapbox-gl-native/issues/2167, unless we make a many-sided polygon instead.

**Comment by friedbunny** [comment]
To be clear, the Mapbox Maps SDK for iOS does not directly offer any geofencing or region monitoring capabilities. For that, [use system-provided Core Location APIs](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/LocationAwarenessPG/RegionMonitoring/RegionMonitoring.html).

**Comment by captainbarbosa** [comment]
I'd like for us to have better support for geofencing, but its unclear what product of ours would offer that, so I'm inclined to close this issue for now.
