### ISSUE TITLE
More fill pattern example follow-up

### ISSUE THREAD

**Issue by friedbunny** [mapbox/ios-sdk-examples#104]
@captainbarbosa Follow-up for #94:

1. Rename the Swift view controller to `FillPatternExample_Swift` so that the Jekyll plugin can regex it to `ViewController`.
2. Set a matching tint color.
3. Delete the Xcode 9 AppIcon entry that got added.

**Comment by captainbarbosa** [comment]
Additional follow-up from @1ec5: https://github.com/mapbox/ios-sdk-examples/pull/94#pullrequestreview-48197643

**Comment by captainbarbosa** [comment]
👉  #105
