### ISSUE TITLE
Drag and drop example

### ISSUE THREAD

**Issue by friedbunny** [mapbox/ios-sdk-examples#110]
We’ve [blogged](https://blog.mapbox.com/integrating-ios-11-drag-and-drop-features-with-mapbox-6cc4db9ae3d3) about how to drag’n’drop in iOS 11 and the next step is to create a permanent example. Changes from the blog’d code are likely to include swapping the static API for a [map snapshot](https://github.com/mapbox/mapbox-gl-native/issues/1701), adapted to show attribution.

Potential upstream changes are tracked in https://github.com/mapbox/mapbox-gl-native/issues/9350.

/cc @jmkiley @captainbarbosa @1ec5

**Comment by jmkiley** [comment]
`MGLMapSnapshotter` has [landed](https://github.com/mapbox/mapbox-gl-native/pull/9891). We could get this example ready for when it lands.

**Comment by friedbunny** [comment]
Drag and drop hasn’t really caught on as an iOS feature, so the need for this hasn’t been borne out.
