### ISSUE TITLE
Add snapshotter example

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/ios-sdk-examples#114]
Once https://github.com/mapbox/mapbox-gl-native/issues/9920 officially lands

**Comment by captainbarbosa** [comment]
Note that this has been added in https://github.com/mapbox/ios-sdk-examples/pull/124 and will go live on [mapbox.com/ios-sdk/examples](https://www.mapbox.com/ios-sdk/examples/) when v3.7.0 of the Mapbox Maps SDK for iOS is released.

**Comment by friedbunny** [comment]
Live: https://www.mapbox.com/ios-sdk/examples/map-snapshotter/
