### ISSUE TITLE
Discussion: 3D Objects above earth

### ISSUE THREAD

**Issue by mrdavidrees** [mapbox/ios-sdk-examples#122]
Hi, We're investigating whether it's possible to place upright view's that are part of the map over the earth as if it was an overlay that was positioned to the earth's normal. 

The goal would be to have our own views that can be placed on the map, having the map tilted to a pitch of 90 degrees, buildings turned on so that you can see the height of the buildings and terrain, and a view that sizes with it's size and distance from the latitude and longitude that it's fixed at.

This is very similar to an overlay implementation except, that the view could be adjusted to sitting 
upright on the map.

Is this accomplishable?

**Comment by friedbunny** [comment]
It sounds like you’re mainly interested in 3D stuff, in which case the [Mapbox Unity SDK](https://www.mapbox.com/unity/) should be your first stop for investigation.
