### ISSUE TITLE
Realistic building and building lighting example

### ISSUE THREAD

**Issue by 1ec5** [mapbox/ios-sdk-examples#144]
Here’s an idea for an example that combines the concepts of 3D building lighting, terrain lighting, and user location tracking:

* Add fill extrusion layers depicting 3D buildings.
* Replace Mapbox Terrain–based fill layers with Mapbox Terrain-RGB–based hillshade layers (mapbox/mapbox-gl-native#11034).
* Turn on MGLMapView’s user heading tracking mode. On each heading update, or as the user rotates the map, adjust the building lighting and terrain lighting to reflect the position of the Sun, considering the user’s location and the direction the device is facing.
   * Use [Solar](https://github.com/ceeK/Solar/) to determine the position of the Sun at a given location.
   * Use [UIInterpolatingMotionEffect](https://useyourloaf.com/blog/motion-effects/) to account for the device being tilted.

This example requires iOS map SDK v4.0.0.

/cc @jmkiley @friedbunny @frederoni @mollymerp

**Comment by 1ec5** [comment]
Alternatively, the example could show how to vary lighting direction based on the position of the Sun at the location being viewed. Whereas the original proposal above simulates a tactile map, this alternative would achieve something closer to a flight simulation look and feel.

**Comment by captainbarbosa** [comment]
We're internally re-evaluating how to render 3D maps, so closing this for now.
