### ISSUE TITLE
Example list should be better organized and more friendly

### ISSUE THREAD

**Issue by friedbunny** [mapbox/ios-sdk-examples#166]
The list of examples in the initial table view should:

- Use the prose name of the example, per the website.
- Be sectioned by category, per the organization on the website.
- Have one entry per example, perhaps containing separate buttons for Obj-C and Swift.

<img src=https://user-images.githubusercontent.com/1198851/39009560-fbbad7f6-43d9-11e8-84d8-aa87aae9948e.jpeg width=300>

/cc @jmkiley @captainbarbosa @lilykaiser

**Comment by lloydsheng** [comment]
@friedbunny  That's what i working at! I was planing cut up a ticket and saw this issue. 😀
Last week i've prepared a demo app for Wework Shanghai Job fair which based on `ios-sdk-examples`. But I think it difficult to find the example I want through looking up controller name list. So i organized examples with category names and add some brief descriptions, here are the screenshots:

### iPad Landscape:
![img_0018](https://user-images.githubusercontent.com/503040/39037222-6ca1188a-44b2-11e8-994b-45ed968fd99f.jpg)

### iPad Portrait:
![img_0019 3](https://user-images.githubusercontent.com/503040/39037432-125b67bc-44b3-11e8-9b4a-1de9b92ab1ff.PNG)

## iPhone:
![img_0002](https://user-images.githubusercontent.com/503040/39037509-4c3eae08-44b3-11e8-88ee-8dee0a522e36.PNG)

 I'm going to:

- [ ] Category name, title, description  localization(English, Chinese)

- [ ] Create a pull request for those changes.

Look forward to your thoughts.

**Comment by lloydsheng** [comment]
@lilykaiser @chriswu42   Video demos:

https://www.dropbox.com/s/v1ghsi1wjp1swxx/Examples-iPad.mp4?dl=0
https://www.dropbox.com/s/q9ktoyaf16ii6ex/Examples-iPhone.mp4?dl=0

**Comment by lilykaiser** [comment]
Looks great!

**Comment by jmkiley** [comment]
Closed via #172
