### ISSUE TITLE
Geocoding example

### ISSUE THREAD

**Issue by 1ec5** [mapbox/ios-sdk-examples#17]
There should be an example in which the user can long-press the map to drop a pin and see its address, geocoded using the Geocoding API via MapboxGeocoder.swift.

/ref #6
/cc @friedbunny @tmcw

**Comment by 1ec5** [comment]
> More broadly, we can consider expanding the /ios-sdk front page with dedicated sections for the Mapbox*.swift libraries, like what we’ve got on [/android-sdk](https://www.mapbox.com/android-sdk/#mapbox_android_services).

/ios-sdk now covers all the SDKs. This project, meanwhile, already depends on the navigation SDK and thus MapboxDirections.swift, so a dependency on MapboxGeocoder.swift doesn’t sound so bad.

**Comment by captainbarbosa** [comment]
>/ios-sdk now covers all the SDKs.

It doesn't anymore 😁 and nav examples were moved to their own repo in https://github.com/mapbox/ios-sdk-examples/pull/324. Because of this, I'm inclined to close this, and keeping examples in [`MapboxGeocoder.swift`](https://github.com/mapbox/MapboxGeocoder.swift) for now.
