### ISSUE TITLE
IOS Add custom Layers on MapView

### ISSUE THREAD

**Issue by sameerakohli** [mapbox/ios-sdk-examples#183]
I want to acchive this functionality in IOS 
<img width="229" alt="screen shot 2018-05-21 at 11 59 52 am" src="https://user-images.githubusercontent.com/34680247/40293508-e49288f2-5cee-11e8-82ef-27b3361da98c.png">

**Comment by jmkiley** [comment]
Thank you for using Mapbox! This repo is for reporting issues with existing examples or requesting new examples. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).
