### ISSUE TITLE
Update building in "Display 3D Buildings" example

### ISSUE THREAD

**Issue by jmkiley** [mapbox/ios-sdk-examples#188]
The `extrude` attribute for the Colosseum is now set to `false`. [The example](https://www.mapbox.com/ios-sdk/examples/extrusions/) should be updated to use a building with extrusions enabled.

**Comment by williamdarkocode** [comment]
I'm tried playing around with the extrude values, but when using 'extrude is any of false' all other buildings cease to extrude

**Comment by jmkiley** [comment]
Hey @williamdarkocode - 

Thanks for testing it out. When the `extrude` property for a building is `false`, that building likely does not have the `height` data that this example uses for extrusions. This is what has happened with the Colosseum. The other buildings still are rendered in 3D, just not the Colosseum.
