### ISSUE TITLE
Add enlarge annotation example

### ISSUE THREAD

**Issue by bsudekum** [mapbox/ios-sdk-examples#189]
Both Google and Apple have made the "select an annotation, make it larger" type animation pretty popular in years past:

Let's add an example that does just this. Nothing too complicated, but should 

1. enlarge the selected annotation
1. shrink any enlarged annotation when deselecting

Maybe we can even talk about adding this into the sdk proper?

/cc @jmkiley @1ec5

**Comment by captainbarbosa** [comment]
[`DraggableAnnotationExample`](https://github.com/mapbox/ios-sdk-examples/blob/905bca86bd355da6a61237ca11a193f2c4fb4dcb/Examples/Swift/DraggableAnnotationViewExample.swift#L115-L126) does this well enough to cover this case.
