### ISSUE TITLE
Bathymetry Styling at Runtime

### ISSUE THREAD

**Issue by riastrad** [mapbox/ios-sdk-examples#200]
It could be useful to have an example of using [MGLFillStyleLayer](https://www.mapbox.com/ios-sdk/api/4.2.0/Classes/MGLFillStyleLayer.html) to add Bathymetry data and style using expressions at runtime.

Bathymetry would be applied similarly to the [North Star](https://www.mapbox.com/designer-maps/#north-star) designer style. 

cc: @jmkiley & @captainbarbosa for thoughts

**Comment by captainbarbosa** [comment]
There are already many examples how to perform data-driven styling, so going to close for now.
