### ISSUE TITLE
Using Line-Gradient Property

### ISSUE THREAD

**Issue by riastrad** [mapbox/ios-sdk-examples#203]
When mapbox/mapbox-gl-native#12575 lands, a new example that demonstrates how to leverage this feature will be very helpful.

Especially as this delivers the ability to implement frequently asked for line animations.

**Comment by 1ec5** [comment]
Note that the `line-gradient` property, like all the data-driven properties, lacks support for transitions: https://github.com/mapbox/mapbox-navigation-ios/issues/1307#issuecomment-414446456. So animating a gradient will require changing the property on each frame on a timer.

**Comment by JanC** [comment]
Hi @riastrad, is your WIP example somehow working? I'm getting the exception

```
'NSInvalidArgumentException', reason: 'Invalid property value: [2][1]: Unknown variable "lineProgress". Make sure "lineProgress" has been bound in an enclosing "let" expression before using it.'
```

**Comment by riastrad** [comment]
@JanC That's correct, while building out that example I ran into the issue you've linked to. I'm currently troubleshooting possible workarounds, but will likely hold off on finalizing this example until that issue is resolved.

**Comment by riastrad** [comment]
Just want to note that `$lineProgress` is an expression variable as of mapbox/mapbox-gl-native#13192, so we should be good to pick rebase on master and pick this back up (since the examples were bumped to v4.6.0 here: https://github.com/mapbox/ios-sdk-examples/pull/244)

**Comment by captainbarbosa** [comment]
We should still do this!

**Comment by jumbopilot** [comment]
Hi guys, yes, would be very much appreciated.
