### ISSUE TITLE
MapBox Foursquare

### ISSUE THREAD

**Issue by grass008** [mapbox/ios-sdk-examples#207]
Hello, MapBox Team

I saw this article https://blog.mapbox.com/mapbox-%EF%B8%8F-foursquare-over-100-million-places-on-the-map-3ccf8d260265 

Want to asked when we can use Foursquare in MapBox?

Thank You for Your time.
Yura

**Comment by captainbarbosa** [comment]
Hi Yura,

Foursquare data is already available in Mapbox maps. Please note that this GitHub repository is for reporting issues and requesting new examples related our Mapbox Maps SDK for iOS. For help with “How do I” questions, or general questions about Mapbox, reach out to our excellent [support team](https://www.mapbox.com/contact/).
