### ISSUE TITLE
UserTrackingModesExample: button does not reset to ‘none’ state

### ISSUE THREAD

**Issue by friedbunny** [mapbox/ios-sdk-examples#213]
The user location toggle button does not reset to its “none” state when the map is “none” — it should be a hollow, uncolored arrow when no user tracking mode is enabled.

![img_f46cb5265dab-1](https://user-images.githubusercontent.com/1198851/44937598-fcc74080-ad47-11e8-927f-a908e3cf9cff.jpeg)

/cc @captainbarbosa

**Comment by captainbarbosa** [comment]
@friedbunny I'm not sure if I can reproduce this - here is a gif of my cycling through the tracking modes on my iPhone X. It looks like when its set to `none` I'm getting the hollowed out arrow:

![userlocation](https://user-images.githubusercontent.com/10850812/45315073-3fc3a980-b4e8-11e8-8227-81095c7e3983.gif)
