### ISSUE TITLE
LineStyleLayerExample style differs between Obj-C and Swift examples.

### ISSUE THREAD

**Issue by julianrex** [mapbox/ios-sdk-examples#220]
Testing with `4.4.0-beta.1`:

### Swift ###
![img_1611](https://user-images.githubusercontent.com/3765757/45229468-dc413e00-b293-11e8-93a1-b1f1a934a641.PNG)
![img_1614](https://user-images.githubusercontent.com/3765757/45229472-e105f200-b293-11e8-87c9-202abd1ec991.PNG)

### Obj-C ###
![img_1612](https://user-images.githubusercontent.com/3765757/45229482-e9f6c380-b293-11e8-805d-f31a99b56850.PNG)
![img_1613](https://user-images.githubusercontent.com/3765757/45229487-ed8a4a80-b293-11e8-8e06-0e73c5e31fbd.PNG)

**Comment by captainbarbosa** [comment]
Still in 4.7.0-beta.2
