### ISSUE TITLE
Move DocsCode/NavigationTutorial to navigation-ios-examples repo

### ISSUE THREAD

**Issue by friedbunny** [mapbox/ios-sdk-examples#222]
[DocsCode/NavigationTutorial](https://github.com/mapbox/ios-sdk-examples/tree/e424c83a03fd33b87e5646a7ba1da81bb5d47915/DocsCode/NavigationTutorial) should be moved to the [navigation-ios-examples repo](https://github.com/mapbox/navigation-ios-examples) — this will unblock us in times where the Nav SDK’s dependency on the Maps SDK lags the latest version (e.g., https://github.com/mapbox/ios-sdk-examples/pull/208), which prevents us from updating this repo.

/cc @mapbox/navigation-ios @captainbarbosa @mapbox/docs

**Comment by friedbunny** [comment]
As we handle new releases for all of the disparate SDKs represented in this repo, the merge conflicts become... annoying. Is there someone from @mapbox/navigation-ios that can take on this task?

**Comment by captainbarbosa** [comment]
Noting this is [blocking us](https://github.com/mapbox/ios-sdk-examples/pull/301) from updating to v5.0.0 of the new Maps SDK until our Navigation SDK upgrades to 5.0.0 as well.

**Comment by friedbunny** [comment]
There’s also an intention to more closely integrate this repo with `gl-native` — perhaps as a submodule or similar. Having navigation examples and dependencies in `gl-native` is not desirable.

**Comment by 1ec5** [comment]
For now, mapbox/mapbox-navigation-ios#2133 upgrades the navigation SDK to require map SDK v5._x_.

**Comment by friedbunny** [comment]
As of https://github.com/mapbox/mapbox-navigation-ios/pull/2143, we can’t update the Maps SDK in this project. If the navigation SDK doesn’t unblock merging #317 in a timely manner, we’ll disable the `DocsCode` target again.

**Comment by 1ec5** [comment]
Also a good example of why backwards-incompatible changes should always go in semver-major releases. 😉 But point taken. mapbox/mapbox-navigation-ios#2134 tracks removing the workaround for the vanishing point issue. Once that lands, we can upgrade to v5.1._x_ without a problem.

**Comment by friedbunny** [comment]
After wrangling merge conflicts in https://github.com/mapbox/ios-sdk-examples/pull/321, I decided to do this myself: https://github.com/mapbox/navigation-ios-examples/pull/43
