### ISSUE TITLE
Custom user location annotation example is jerky when panning

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/ios-sdk-examples#224]
The annotation used for the custom user location example is jerky at times when panning across the map. This doesn't happen all the time but can usually be triggered by moving the annotation off of the map view and then moving it back into view.

I wasn't able to capture this in a low-quality gif but you can observe this when running the example on a physical device.

**Comment by julianrex** [comment]
This still happens with `4.5.0-beta.1` but looks like only when the location is updating while the user is panning (I suspect that there two code paths that are trying to update the position simultaneously.)

**Comment by friedbunny** [comment]
If this is still an issue, let’s continue tracking it in `gl-native`.
