### ISSUE TITLE
Need to implement example for autocomplete feature in iOS

### ISSUE THREAD

**Issue by rgrathnakumar** [mapbox/ios-sdk-examples#229]

**Comment by captainbarbosa** [comment]
Hi @rgrathnakumar — thanks for using Mapbox. This repo is for reporting bugs and coordinating work for examples related to the Mapbox Maps SDK for iOS. For help with implementation and "How do I" type questions, please ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox) or reach out to our excellent [support team](https://www.mapbox.com/contact/support/).
