### ISSUE TITLE
PolygonPatternExample - fill appears "bent"

### ISSUE THREAD

**Issue by julianrex** [mapbox/ios-sdk-examples#233]
In https://github.com/mapbox/ios-sdk-examples/tree/ios-v4.5.0 (at https://github.com/mapbox/ios-sdk-examples/commit/4d48f554fb0772bbf911d590ae70a6f2c9fe406a built with `4.5.0-beta.1`), when running `PolygonPatternExample` the fill appears bent at the edge of the circle:

![img_1738](https://user-images.githubusercontent.com/3765757/46514968-08b68e80-c82f-11e8-9ffb-4a8cc56929ac.PNG)

/cc @mollymerp

**Comment by mollymerp** [comment]
Is this a new issue with the most recent release, or did you just notice it?

**Comment by julianrex** [comment]
I only noticed it with this release - I don't know if it was there before or not 😞 

Looking at @friedbunny's gif in the  [issue that you fixed](https://github.com/mapbox/mapbox-gl-native/issues/12790), I don't see the same artifact (but it's not the same area of the circle).

I'm going to close this ticket, and open a new one in mapbox-gl-native.

**Comment by julianrex** [comment]
Closed in preference of https://github.com/mapbox/mapbox-gl-native/issues/13081
