### ISSUE TITLE
A way to reorder layers

### ISSUE THREAD

**Issue by BrunooShow** [mapbox/ios-sdk-examples#236]
I'm looking for a way to move to front or behind a specific layer, is it possible, any alternative?
removing and inserting in position is the only way?

**Comment by lloydsheng** [comment]
Hi  — thanks for using Mapbox. This repo is for reporting bugs and coordinating work for examples related to the Mapbox Maps SDK for iOS. For help with implementation and "How do I" type questions, please ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox) or reach out to our excellent [support team](https://www.mapbox.com/contact/support/).
