### ISSUE TITLE
UISlider for RasterImagery and BuildingLight examples overlaps wordmark and attribution

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/ios-sdk-examples#239]
On an iPhone X, the `RasterImagery` and `BuildingLight` examples overlap the Mapbox wordmark and attribution. The fix would involve adjusting the positioning of the UISlider's frame.

**Comment by friedbunny** [comment]
Shall we consolidate these in #164?

**Comment by captainbarbosa** [comment]
Sure. Closing in favor of #164.
