### ISSUE TITLE
Showing a hidden layer button overlaps with iPhone X's gesture bar.

### ISSUE THREAD

**Issue by fabian-guerra** [mapbox/ios-sdk-examples#243]
In Show Hide Layer Example on both ObjC and Swift the toggle button overlaps with the iPhone X gesture bar.

![img_8647348b96d8-1](https://user-images.githubusercontent.com/2745166/47317989-b97aa700-d5ff-11e8-87b4-69c81d521c78.jpeg)

**Comment by captainbarbosa** [comment]
Duplication of https://github.com/mapbox/ios-sdk-examples/issues/164
