### ISSUE TITLE
In both Clustering Examples - cluster number appears to jump out-of-sync with the surrounding circle.

### ISSUE THREAD

**Issue by julianrex** [mapbox/ios-sdk-examples#246]
Testing with `4.6.0-beta.1`:

![screen recording 2018-11-01 at 02 24 pm](https://user-images.githubusercontent.com/3765757/47893361-fd0cb680-de32-11e8-9190-5e05c26cea52.gif)

The cluster number appears to jump, making this seem like a bug. However I suspect this is more of an optical illusion: notice that the numbers fade in/out, whereas the circle jumps to the new cluster location.

Can we improve this example by not fading the numbers?

**Comment by captainbarbosa** [comment]
Yup, this is still a thing.

**Comment by julianrex** [comment]
@tmpsantos please close if stale.
