### ISSUE TITLE
SelectFeatureExample stopped working with v4.8.0-alpha.1

### ISSUE THREAD

**Issue by fabian-guerra** [mapbox/ios-sdk-examples#263]
The example `SelectFeatureExample` on both objc and swift with the SDK version `4.8.0-alpha.1` stopped working.

**Comment by captainbarbosa** [comment]
I can't reproduce this issue on my iPhone X on iOS v12.1.2 🤔

**Comment by friedbunny** [comment]
Perhaps https://github.com/mapbox/ios-sdk-examples/pull/269.

**Comment by friedbunny** [comment]
Err, no — `SelectFeatureExample` _is a different example_ than `FeatureSelectionExample`... 🤨

... perhaps it’s time to rationalize these names.

**Comment by fabian-guerra** [comment]
I was referring to "Select a park feature" (`SelectFeatureExample_Swift`/`SelectFeatureExample.m`, I checked today with `java-beta.1` and I can still reproduce the issue. Perhaps is something similar to #269

**Comment by jmkiley** [comment]
It doesn't look like the `SelectFeatureExample` is pinned to a Mapbox Streets style version, so it may be broken for Mapbox Streets v11. Setting the style URL for the Objective-C example to `[MGLStyle streetsStyleURLWithVersion:10];` seems to fix it for me.

**Comment by jmkiley** [comment]
Addressed in #270
