### ISSUE TITLE
How to read offline pack

### ISSUE THREAD

**Issue by RahulGusain** [mapbox/ios-sdk-examples#277]
How to read offline pack when application is offline, I have downloaded pack , now i want to read pack and show map offline.

All i want is to show the tiles downloaded in map when application is opened offline

**Comment by riastrad** [comment]
@RahulGusain, as long as you have correctly downloaded the region and the map is initializing within this region, there are no additional steps needed. The map will load as it usually does. However, if the user attempts to navigate outside of the region while offline they will see a blank map background.

Also please note that this repo is for managing the work around creating and updating example uses of the Mapbox iOS Maps SDK. For future requests such as "How do I implement this?" or "Is it possible to?" please [reach out to our Support team directly](https://support.mapbox.com/hc/en-us).

**Comment by RahulGusain** [comment]
Thank you very much , after passing correct region bounds i got map offline working.
