### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by necatievrenyasar** [mapbox/ios-sdk-examples#279]
I have been creating a framework that use mapbox. When I released my framework from CocoaPods, I toke a  following error.

`/Users/evrenyasar/Xcode/RockApp2/Pods/Target Support Files/Pods-RockApp2/Pods-TestApp-frameworks.sh: line 114: local: `/Users/evrenyasar/Xcode/TestFramework/Pods/Mapbox-iOS-SDK/dynamic/826E141E-8875-3C3B-A106-2B772F8A0684.bcsymbolmap': not a valid identifier
Command PhaseScriptExecution failed with a nonzero exit code`

How can I solve this problem?

**Comment by friedbunny** [comment]
That appears to be an issue with CocoaPods — 1.7.0 pre-releases attempt to preserve bcsymbolmaps, but fail.
