### ISSUE TITLE
WMS

### ISSUE THREAD

**Issue by 1ec5** [mapbox/ios-sdk-examples#28]
Port https://www.mapbox.com/mapbox-gl-js/example/wms/ to the iOS SDK. Requires iOS SDK v3.4.0-alpha.1 for the runtime styling API and WMS support.

/cc @friedbunny @tmcw

**Comment by captainbarbosa** [comment]
@1ec5 I believe this is covered in https://github.com/mapbox/ios-sdk-examples/blob/f70b74d5a3f7f24fae1f150aa4da23daa2dd58bb/Examples/Swift/RasterImageryExample.swift#L27, but feel free to re-open if you think they're not related.

**Comment by friedbunny** [comment]
@captainbarbosa WMS is a different protocol for serving tiled maps — [here’s an example of `WMS`](https://github.com/mapbox/mapbox-gl-native/blob/d169ea55c1cfa85cd8bf19f94c5f023569f71810/platform/macos/app/wms.json#L8). The example you linked to instead uses `XYZ` ([more here](https://en.wikipedia.org/wiki/Tiled_web_map)).

[More on various tile-serving protocols.](https://gis.stackexchange.com/questions/132242/what-are-the-differences-between-tms-xyz-wmts)

... in any case, I think we’re fine in omitting a WMS example.

**Comment by ianthetechie** [comment]
I would argue that an example would be incredibly helpful. Either that or more obvious info about the acceptable format string placeholders. After much searching, I found this in the mapbox-gl-native docs (https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/docs/guides/Tile%20URL%20Templates.md) when I needed to add a WMS layer for a client.
