### ISSUE TITLE
Create offline example using a multipolygonal offline region

### ISSUE THREAD

**Issue by julianrex** [mapbox/ios-sdk-examples#280]
@1ec5 Hi, I'm having performance issues downloading too many offline regions, could you please share some example of the multipolygon approach?

_Originally posted by @pedrocruzlopez in https://github.com/mapbox/mapbox-gl-native/issues/6651#issuecomment-473373677_

**Comment by captainbarbosa** [comment]
Is this the same as https://github.com/mapbox/ios-sdk-examples/issues/280?

**Comment by captainbarbosa** [comment]
Duplicate of https://github.com/mapbox/ios-sdk-examples/issues/206?
