### ISSUE TITLE
Using custom style crashes ClusteringExample.swift when tapping on the map

### ISSUE THREAD

**Issue by topinvestor** [mapbox/ios-sdk-examples#281]
https://github.com/mapbox/ios-sdk-examples/blob/master/Examples/Swift/ClusteringExample.swift

When using <MY STYLE> like this:
--
        let styleURL = URL(string: "mapbox://styles/<MY STYLE>")
        let mapView = MGLMapView(frame: view.bounds,
                                 styleURL: styleURL)
        mapView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        mapView.delegate = self
             view.addSubview(mapView)
--

The example crashes when taping on the map here:

Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

At this location of the code:
 @objc func handleMapTap(sender: UITapGestureRecognizer) {
        
        **guard let source = mapView.style?.source(withIdentifier: "clusteredPorts") as? MGLShapeSource** else {
            return
        }

**Comment by captainbarbosa** [comment]
Hi @topinvestor, I wasn't able to replicate this. If you still see this error after updating this project to its latest version please open a new issue. Thanks!

**Comment by jaksatomovic** [comment]
same here, any news?

**Comment by captainbarbosa** [comment]
@jaksatomovic which Maps SDK version are you trying this on?

**Comment by jaksatomovic** [comment]
@captainbarbosa 5.8

**Comment by jaksatomovic** [comment]
I could really use help, anyone?

**Comment by jmkiley** [comment]
Hi @jaksatomovic - 

Are you also seeing a crash at the the `guard` statement? I am also unable to see this issue with a custom style. Are you adding a source to your map that has the identifier `"clusteredPorts"`, or are you checking for a source with a different identifier?

**Comment by jaksatomovic** [comment]
Finally found a mistake, I had double initialization, you can close this issue now. thx
