### ISSUE TITLE
Tiptoe around border disputes

### ISSUE THREAD

**Issue by 1ec5** [mapbox/ios-sdk-examples#29]
We should have an example of restyling certain sets of disputed borders. We can go a step further, using `NSLocale.countryCode` or `CTCarrier.isoCountryCode` to erase borders based on the country we detect the user is located in.

This will require iOS SDK v3.4.0 for the runtime styling API.

/cc @friedbunny @pveugen @frederoni

**Comment by friedbunny** [comment]
This would be a fine thing for a third party to implement, should they have the need.

**Comment by 1ec5** [comment]
This would be a fine plugin for us to implement, as evidenced by [mapbox-gl-boundaries](https://github.com/mapbox/mapbox-gl-boundaries/).

**Comment by 1ec5** [comment]
This would be a fine plugin for us to implement, as evidenced by [mapbox-gl-boundaries](https://github.com/mapbox/mapbox-gl-boundaries/).

/cc @ericrwolfe
