### ISSUE TITLE
Set color of a specific featureid (polygon) after a tap

### ISSUE THREAD

**Issue by skrypchenkomaksym** [mapbox/ios-sdk-examples#344]
I have an iOS app which has a following scenario:

1. User sees a map full of grey buildings and only some of them are yellow.
2. User taps on a yellow building and this only building changes its color to green. A pop-up windows is displayed
3. User closes the window and the green building changes its color to pink. After that this windows is always pink. Only if user taps it again - it's green only while the pop-up window is displayed.

We have one layer with all polygons (buildings). Based on the filter word, some of them are grey and some of them are yellow.Each buildings is assigned its unique polygon id (pid)

What we've tried: Using NSpredicate colored the whole layer, not only one specific layer. We can't figure out how to make mapbox understand that a specific building should be colored, not the whole layer. So the answer should be linked to a specific polygon id.

Here is an example of GeoJson we use: (pid = featureid; if "av":0 - the buildings are grey , if "av":1 - yellow.
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "pid": 1,
        "color": "black",
        "av": 0,
        "height": 21.60850812,
        "Address": "588 Egan Street, Brooklyn, New York, New York 11208, United States",
        "Borough": "Brooklyn",
        "Price": "$3,393–$6,763+",
        "Number_of_bedrooms": "Studio – 3 bd",
        "Number_of_bathrooms": "1 –2 ba",
        "Area": "396 – 1,406 sqft+",
        "URL": "https://www.trulia.com/c/ny/brooklyn/180-montague-180-montague-st-brooklyn-ny-11201--2009534594",
        "images": [
          "https://static.trulia-cdn.com/pictures/thumbs_3/ps.113/2/6/8/d/picture-uh=16b997252fa447565647e53e76ee89-ps=268d74538d16ea5ad1afd314c09e4ce.webp",
          "https://static.trulia-cdn.com/pictures/thumbs_3/ps.113/2/6/8/d/picture-uh=16b997252fa447565647e53e76ee89-ps=268d74538d16ea5ad1afd314c09e4ce.webp"
        ],
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
      },
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                -73.87129515296562,
                40.65717370043455
              ],
              [
                -73.87135858020156,
                40.65714663518705
              ],
              [
                -73.87143322008981,
                40.6572480836196
              ],
              [
                -73.87136979278591,
                40.6572751498085
              ],
              [
                -73.87129515296562,
                40.65717370043455
              ]
            ]
          ]
        ]
      }
    }
  ]
}

**Comment by jmkiley** [comment]
Thank you for using Mapbox! This repo is for reporting issues with examples or requesting new examples. The answer to many "how do I...?" questions can be found in our [help documentation](https://github.com/mapbox/gl-internal/issues/1100) and [examples](https://docs.mapbox.com/ios/maps/examples/). You may find the [feature selection example](https://docs.mapbox.com/ios/maps/examples/select-layer/) helpful. If you can't find the answer there, the best place to ask is on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox). Mapbox Support team members actively contribute there.
