### ISSUE TITLE
Update examples to iOS 13 & Swift 5

### ISSUE THREAD

**Issue by julianrex** [mapbox/ios-sdk-examples#348]
We need to:

- [x] Ensure examples build and run with iOS 13 & Xcode 11
- [X] ~Convert Swift examples to Swift 5~ Already done in https://github.com/mapbox/ios-sdk-examples/pull/316

**Comment by julianrex** [comment]
Let's check to see if there are any changes needed for Swift 5.1

**Comment by julianrex** [comment]
See also https://github.com/mapbox/ios-sdk-examples/issues/338

**Comment by captainbarbosa** [comment]
No changes needed for Swift 5.1 ⭐️
