### ISSUE TITLE
Multiple images in one layer

### ISSUE THREAD

**Issue by Swiftocrat** [mapbox/ios-sdk-examples#350]
Hello, I want to add multiple images on map, but MGLImageSource can take only one image, so I should create new layer for every image, which will be bad decision for app performance. 

Can I use some other method to do this ? Need your advice.
Thank you.

**Comment by captainbarbosa** [comment]
Hi @Swiftocrat  — thanks for using Mapbox. 

I'm not aware of the details of your use case, but if you don't need to georeference the edges of your image, you may want to consider using an `MGLSymbolStyleLayer` with multiple images, as shown [in this example](https://github.com/mapbox/ios-sdk-examples/blob/master/Examples/Swift/MultipleImagesExample.swift).

Using multiple image layers won't inherently affect performance, its all about how many layers you're adding and how many images need to be loaded into the style. So, you may only notice performance issues once you hit a certain threshold. 

By the way, this repo is for reporting bugs, requesting features, and coordinating work related to the various Mapbox Map SDKs. For help with “how do I” questions, we ask in the future that you check out our [StackOverflow page](https://stackoverflow.com/questions/tagged/mapbox) or reach out to our excellent [support team](https://www.mapbox.com/contact/support/). Thanks!
