### ISSUE TITLE
Automatically localize to user preferred language

### ISSUE THREAD

**Issue by 1ec5** [mapbox/ios-sdk-examples#36]
We should have an example that localizes a Mapbox Streets–sourced style on the fly according to the user’s preferred language. It’d be similar to the code added in mapbox/mapbox-gl-native#6819, except that a hard-coded list of layers would be unnecessary because we’d iterate over all the symbol layers.

Requires v3.4.0 for the runtime styling API. mapbox/mapbox-gl-native#7031 would completely obviate this example.

/cc @friedbunny

**Comment by 1ec5** [comment]
https://github.com/mapbox/mapbox-gl-native/blob/8eb23cbac8a6c5821dc5935e27689700216c3f1a/platform/macos/app/MapDocument.m#L340-L387

**Comment by friedbunny** [comment]
This will be a feature in v3.6.2, via https://github.com/mapbox/mapbox-gl-native/pull/9582.
