### ISSUE TITLE
map.visibleFeatures(at: #CGPoint#, styleLayerIdentifiers: #Set#) always return 1 object in array

### ISSUE THREAD

**Issue by bobandiga** [mapbox/ios-sdk-examples#372]
We have a style in the studio, it has a 3D layer that is connected to a custom source from the studio. When developing for SWIFT, we connect to the style, change its color, height. But when we tap on the polygon, we always get ONE object in the array using map.visibleFeatures (at: <# T ## CGPoint #>, styleLayerIdentifiers: <# T ## Set <String>? #>)

**Comment by captainbarbosa** [comment]
Hi @bobandiga  — thanks for using Mapbox. This GitHub repository is only intended to track the development of examples that use the Mapbox Maps SDK for iOS. 

For help with specific implementations or other “how do I do X” questions, or help troubleshooting installation, please ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox) or reach out to our excellent [support team](https://www.mapbox.com/contact/support/).
