### ISSUE TITLE
UISlider update events result in compute-intensive apis being called on main thread, causing laggy behavior and occasional crash.

### ISSUE THREAD

**Issue by nishant-karajgikar** [mapbox/ios-sdk-examples#375]
In the `BuildingLightExample` and `RasterImageryExample` (and their swift counterparts), a `UISlider` is used to allow the user to play with various effects. This slider however is currently configured to be `continuous` and as a result invokes it's selector (on main thread) on every update event. 

Since the mapbox operations are compute-intensive this causes laggy behavior in simulators (and the occasional crash on Xcode).

**Comment by captainbarbosa** [comment]
👍 Good point, I agree thats a good change!
