### ISSUE TITLE
Examples' page formatting on mobile

### ISSUE THREAD

**Issue by jmkiley** [mapbox/ios-sdk-examples#41]
You can only see Swift examples when viewing the iOS Examples page on Mobile in Safari. The examples list is not present in portrait mode.

<img width="309" alt="screenshot 2016-12-08 15 58 28" src="https://cloud.githubusercontent.com/assets/12474734/21032578/33091400-bd5f-11e6-8897-0515f34b3942.png">

**Comment by friedbunny** [comment]
This issue with the site has been fixed.
