### ISSUE TITLE
Fix line wrapping on examples

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/ios-sdk-examples#43]
The line wrapping on some of the examples is too constrained, resulting in [longer examples](https://www.mapbox.com/ios-sdk/examples/line-geojson/) that look like this:

<img width="740" alt="screen shot 2016-12-09 at 3 16 48 pm" src="https://cloud.githubusercontent.com/assets/10850812/21067821/a5fac65c-be22-11e6-9b65-021874da15cc.png">

cc @friedbunny

**Comment by 1ec5** [comment]
If possible, we should find a way to keep the line wrapping but introduce a hanging indent for any wrapped lines (for consistency with Xcode, which wraps lines by default).

This particular example code was eviscerated in #78. If there are any other examples with such severe indentation, we should find a way to refactor the code to be more readable regardless of line wrapping.

**Comment by 1ec5** [comment]
Assuming the excessive indentation is no longer an issue, we can also insert hard breaks strategically (e.g., between arguments) to avoid the need to wrap lines or scroll horizontally.

**Comment by captainbarbosa** [comment]
https://www.mapbox.com/ios-sdk/ has been redesigned, and now includes a wider area for code to be displayed.
