### ISSUE TITLE
Use built-in JSON serialization in GeoJSON line example

### ISSUE THREAD

**Issue by friedbunny** [mapbox/ios-sdk-examples#45]
We’re adding JSON serialization (https://github.com/mapbox/mapbox-gl-native/issues/3630#issuecomment-266323262) for MGLShape in https://github.com/mapbox/mapbox-gl-native/pull/7377. This means we can ditch the manual serialization in the existing GeoJSON line example, making it much cleaner and easier to follow.

/cc @1ec5

**Comment by friedbunny** [comment]
Fixed in #78.

**Comment by 1ec5** [comment]
It’s a lot easier to follow! 🎉
