### ISSUE TITLE
Add managing memory resources example (with multiple active full screen maps)

### ISSUE THREAD

**Issue by boundsj** [mapbox/ios-sdk-examples#52]
It is common for iOS applications to have many view controllers on the nav stack (think about surfing through user profiles in a social networking app where you may keep adding views like cards on a deck as you walk through a social graph).

We should consider adding an example that illustrates some approaches for keeping memory usage (RAM) streamlined in this situation.

**Comment by captainbarbosa** [comment]
@boundsj I'm thinking this might be better as a guide, maybe in our [API docs](https://www.mapbox.com/ios-sdk/api/) - what do you think?

**Comment by boundsj** [comment]
Sounds good to me!

**Comment by captainbarbosa** [comment]
🙇 🆒

**Comment by boundsj** [comment]
@captainbarbosa for reference, [here](https://github.com/mapbox/lp-collab/issues/23) is the LP issue that prompted this suggestion. And, [something new](https://github.com/mapbox/mapbox-gl-native/issues/9203) in the same vein.
