### ISSUE TITLE
Lint examples

### ISSUE THREAD

**Issue by 1ec5** [mapbox/ios-sdk-examples#55]
We should use [SwiftLint](https://github.com/realm/SwiftLint) to enforce coding conventions automatically, since we tend to care more about code style in our examples than in other code we write.

/cc @friedbunny

**Comment by friedbunny** [comment]
The line between “linting” (static analysis that identifies logical issues) and “formatting” (mainly aesthetic reorganization) is a bit blurred, but I think we could benefit from both. SwiftLint focuses on linting (obvs) and also will reformat, but only for Swift code.

Some options to investigate:
- SwiftLint (Swift, linting and formatting)
- https://github.com/nicklockwood/SwiftFormat (Swift, formatting)
- https://clang.llvm.org/docs/ClangFormat.html (Obj-C, formatting)
- http://oclint.org (Obj-C, linting)
- http://fbinfer.com (Obj-C, linting)

**Comment by julianrex** [comment]
Adding to @friedbunny's list, there's also http://fauxpasapp.com/ which I've had good experience with.

**Comment by captainbarbosa** [comment]
With the impending changes coming to this project, we'll require all new examples to be written in Swift. Their Objective-C counterparts will now be optional, so I think we should focus efforts elsewhere.
