### ISSUE TITLE
Query visible features at point example

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/ios-sdk-examples#57]
I think it would be useful to show how [`(-visibleFeaturesAtPoint:
)`](https://www.mapbox.com/ios-sdk/api/3.4.1/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)visibleFeaturesAtPoint:) works in action - perhaps its time for an example?

**Comment by captainbarbosa** [comment]
This exists in the following example: https://github.com/mapbox/ios-sdk-examples/blob/f70b74d5a3f7f24fae1f150aa4da23daa2dd58bb/Examples/Swift/FeatureSelectionExample.swift#L55

**Comment by skrypchenkomaksym** [comment]
When I use mapView.visibleFeatures(at: spot) - I get only last array item (I have multiple objects contained in the polygon).
How can I get all array items?

**Comment by captainbarbosa** [comment]
@skrypchenkomaksym are they all within the same layer?

**Comment by skrypchenkomaksym** [comment]
Yes. One source and one layer.

**Comment by captainbarbosa** [comment]
@skrypchenkomaksym Are you able to share your source data here and a sample query you're making to provide a minimal test case? Without more information its impossible to troubleshoot, since there could be multiple causes. If you'd rather keep your project private, please reach out to our [support team](https://support.mapbox.com/hc/en-us).

**Comment by skrypchenkomaksym** [comment]
Here is the [sample source ````.geojson```` which is then converted into ````.mbtiles````](https://pastebin.com/0x6gPZU3)  (if you need ````.mbtiles```` just tell me) when I connected to a style layer. As I've said, I don't get an array of items which are contained in one polygon, just the last one. So here is the list of steps I tried:
1. I connected to a source directly using [this code](https://pastebin.com/QnVhBvRW)
2. Now I can't make a layer from that source using [this code](https://pastebin.com/SsyHB53E)

I guess I don't need step 2 but I can't get the whole array with all items as a result of the tap at the polygon.

Once more, expected result: 
I tap at the polygon and get an array of items contained. Specifically, I am getting rental listing in a building.

**Comment by skrypchenkomaksym** [comment]
@captainbarbosa is there any solution for my problem?

**Comment by captainbarbosa** [comment]
@skrypchenkomaksym It currently is not possible to get visible features with in a polygon. 

As noted in our [API documentation](https://docs.mapbox.com/ios/api/maps/5.4.0/Classes/MGLMapView.html#/Accessing%20the%20Underlying%20Map%20Data), feature querying is only supported for specific points with 
`-visibleFeaturesAtPoint:`, or within rectangles by using `-visibleFeaturesInRect:`.

If you have additional questions about our SDK, please contact our [support team](https://support.mapbox.com/hc/en-us).

**Comment by skrypchenkomaksym** [comment]
@captainbarbosa Thanks, I’ll try to do it via connecting to source. But there is a similar problem with it. It is described [here](https://stackoverflow.com/questions/53313021/mapbox-how-to-get-features-for-vector-tile-source). I know it’s not much related to this GitHub issue but I would appreciate your help.
