### ISSUE TITLE
Use this repo to support `pod try` for the iOS SDK

### ISSUE THREAD

**Issue by friedbunny** [mapbox/ios-sdk-examples#59]

**Comment by friedbunny** [comment]
I suspect `pod try` may now be supported by dint of https://github.com/mapbox/mapbox-gl-native/pull/10524.

**Comment by captainbarbosa** [comment]
@friedbunny if this is still something that would be feasible, can you please note here? Otherwise I would like to close this issue.

**Comment by friedbunny** [comment]
CocoaPods is becoming less relevant and I don’t think we should invest time in improving our support for it.
