### ISSUE TITLE
Directions route line example

### ISSUE THREAD

**Issue by 1ec5** [mapbox/ios-sdk-examples#6]
We need an example for taking an MBRoute from MapboxDirections.swift and transforming it into an MGLPolyline that can be displayed on an MGLMapView. The intricacies of MapboxDirections.swift itself should go in https://www.mapbox.com/api-documentation/#directions .

/cc @bsudekum @friedbunny

**Comment by friedbunny** [comment]
See the [Mapbox Navigation SDK for iOS](https://github.com/mapbox/mapbox-navigation-ios) or MapboxDirections.swift for examples of how to integrate directions into an app.
