### ISSUE TITLE
Custom user dot

### ISSUE THREAD

**Issue by 1ec5** [mapbox/ios-sdk-examples#61]
Let’s add an example of customizing the user location annotation view, somewhere along the lines of the existing [annotation view](https://www.mapbox.com/ios-sdk/examples/annotation-views/) example, since it may not be entirely obvious from the MGLMapView API how to do that.

/cc @friedbunny @frederoni

**Comment by 1ec5** [comment]
Oh, this is happening in #50. 🎉

**Comment by friedbunny** [comment]
There have been two starts at this, yeah — #30 and #50.

**Comment by captainbarbosa** [comment]
This happened in #50 🥇
