### ISSUE TITLE
User tracking mode example

### ISSUE THREAD

**Issue by 1ec5** [mapbox/ios-sdk-examples#7]
Until we have a set-it-and-forget-it MGLUserTrackingBarButtonItem (mapbox/mapbox-gl-native#1093), we need an example for a button that cycles among the user tracking modes.

/cc @friedbunny

**Comment by captainbarbosa** [comment]
@friedbunny Is this something you'd be able to finish? Otherwise I'd be happy to take over this in the next few weeks.

**Comment by friedbunny** [comment]
Have at it, @captainbarbosa.

**Comment by friedbunny** [comment]
We finished this in #151.
