### ISSUE TITLE
Datasets API

### ISSUE THREAD

**Issue by 1ec5** [mapbox/ios-sdk-examples#72]
We should have examples for working with data sets authored in Mapbox Studio, specifically for using the Datasets API to populate a shape source. The example in #69 dealt with a relatively small amount of immutable data that was more appropriate for a bundled GeoJSON file, but a data set–focused example would use a larger data set containing the kind of data that would naturally vary over time.

We don’t have a client library for the Datasets API yet like we do for the Geocoding, Directions, and classic Static APIs. From the code originally pushed to #69, it looks like the developer wouldn’t have to do much with the API to display the data set. So let’s focus on display; something more advanced like modifying or deleting data can wait until we have a proper client library.

/cc @jmkiley @captainbarbosa @friedbunny

**Comment by roesneb** [comment]
Hi, 
are there any plans to make the dataset api accessible by the IOS and Android SDK's?
Or does the access have to be self implemented using the REST API?

**Comment by 1ec5** [comment]
For now, you need to use NSURLSession or NSURLConnection if you want to interact directly with the Datasets API. However, the map SDK does allow you to add a dataset to the map by passing its mapbox:// URL into the MGLVectorTileSource initializer.
