### ISSUE TITLE
View syncing example

### ISSUE THREAD

**Issue by 1ec5** [mapbox/ios-sdk-examples#8]
Even after we implement mapbox/mapbox-gl-native#1784, developers may still need to synchronize native views with the map, for example in cases where the view doesn’t quite behave like a point feature. We should add an example that exercises the geometric conversion methods in MGLMapView.

/cc @friedbunny

**Comment by captainbarbosa** [comment]
Its been three years, so I'm going to close this now that style layers exist and we'd like to try to promote their use as much as possible.
