### ISSUE TITLE
Image Source Example

### ISSUE THREAD

**Issue by jmkiley** [mapbox/ios-sdk-examples#93]
It would be great to have an example for how to use [imageSource](https://github.com/mapbox/mapbox-gl-native/pull/9110) once it lands. It has been a pretty commonly requested feature.

cc @captainbarbosa @friedbunny

**Comment by captainbarbosa** [comment]
Note that this has been added in https://github.com/mapbox/ios-sdk-examples/pull/120 and will go live on [mapbox.com/ios-sdk/examples](https://www.mapbox.com/ios-sdk/examples/) when v3.7.0 of the Mapbox Maps SDK for iOS is released.
