### ISSUE TITLE
Rename heat map to hotspot map

### ISSUE THREAD

**Issue by 1ec5** [mapbox/ios-sdk-examples#98]
The “heat map” example added in #87 actually displays a hotspot map: mapbox/DEPRECATED-mapbox-gl#27. Heat maps are a separate feature that we’re working on and will want to [make a splash about](https://www.mapbox.com/blog/heatmaps-preview/) in the not-too-distant future. We should rename the example to avoid confusion.

/cc @jmkiley @friedbunny @captainbarbosa @mourner

**Comment by jmkiley** [comment]
Addressed in https://github.com/mapbox/ios-sdk-examples/pull/97/
